---

user:
  name: b08x
  group: b08x
  uid: 1000
  gid: 1000
  home: /home/b08x
  secondary_groups: "input,video,audio"
  shell: /usr/bin/zsh
  email: rwpannick@gmail.com
  realname: Robert Pannick
  gpg: 36A6ECD355DB42B296C0CEE2157CA2FC56ECC96A
  dots: git@github.com/b08x:dots.git

workspace: "{{ user.home }}/Workspace"

autofs_client:
  host: bender
  shares:
    - Archive
    - Documents
    - Downloads
    - Images
    - Library
    - Music
    - Notebooks
    - Recordings
    - Sessions
    - Videos
    - Workspace


devices:
  daskeyboard: 'ninjabot'
  dell_keyboard_kb216: 'soundbot'
  dictaphone_powermicII: 'ninjabot'
  logitech_mouse_g403: 'soundbot'
  logitech_mouse_g402: 'ninjabot'
  nuance_hid_mouse: 'soundbot'
  nuance_powermicIINS: 'soundbot'
  sayo_keypad: 'soundbot'
