---

- name: enable systemd-timesyncd service
  systemd:
    name: systemd-timesyncd
    enabled: yes

- name: reload firewalld
  shell: "firewall-cmd --reload"
  ignore_errors: True

- name: enable autofs service
  systemd:
    name: autofs
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
