---

- name: enable systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes

- name: reload firewalld
  ansible.builtin.shell: "firewall-cmd --reload"
  ignore_errors: True

- name: enable autofs service
  ansible.builtin.systemd:
    name: autofs
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
