---
#TODO: find out why you would pass RUNLEVEL=1 to perform this task....
- name: Ensure RPM official nginx key
  ansible.builtin.rpm_key:
    key: http://nginx.org/keys/nginx_signing.key
  environment: "{{ nginx_env }}"
  when: ansible_os_family == 'RedHat'

- name: Ensure YUM official nginx repository
  ansible.builtin.template:
    dest: /etc/yum.repos.d/nginx.repo
    src: nginx.repo.j2
  when: ansible_os_family == 'RedHat'