---
- name: Ensure RPM passenger-phusion key
  ansible.builtin.rpm_key:
    key: https://packagecloud.io/gpg.key
    validate_certs: 'yes'
  when: ansible_os_family == 'RedHat'
  tags: [configuration,nginx]

- name: Ensure passenger yum repo file exists
  ansible.builtin.template:
    dest: /etc/yum.repos.d/passenger.repo
    src: nginx.repo.j2
  when: ansible_os_family == 'RedHat'
  tags: [configuration,nginx]

- name: force yum to import gpgkey
  ansible.builtin.shell: yum -qy repolist
  tags: [configuration,nginx]