---

autofs_dir: /etc/autofs

admin_group: wheel

packages:
  # kernel:
  - linux-rt-lts
  - linux-rt-lts-headers
  - dkms
  # networkmanager:
  - network-manager-applet
  - networkmanager
  - nm-connection-editor
  # bluetooth:
  - bluez-utils
  - bluetooth-autoconnect
  # system:
  # - pandoc
  - autofs
  - autojump
  - aria2
  - aribb24
  - atool
  - autoconf
  - automake
  - base-devel
  - bat
  - bc
  - bibtool
  - bind
  - binutils
  - bison
  - bluez-utils
  - boost
  - brightnessctl
  # - btrfsmaintenance
  - ccache
  - cmake
  - cppunit
  - cpupower
  - dialog
  - dmidecode
  - exa
  - faad2
  - fakeroot
  - fasd
  - fd
  - file
  - findutils
  - firewalld
  - flex
  - fwupd
  - fzf
  - gawk
  - gcc
  - gcc-libs
  - gendesk
  - gettext
  - git
  - git-filter-repo
  - git-lfs
  - glibc
  - glow
  - gnu-netcat
  - graphicsmagick
  - grep
  - groff
  - gtkmm
  - gum
  - gzip
  - help2man
  - htop
  - hunspell
  - iftop
  - imlib2
  - inetutils
  - iotop
  - jansson
  - jq
  - kitty
  - kitty-terminfo
  - libbluray
  - libev
  - libgit2
  - libgme
  - libmad
  - libnm
  - libnma
  - libopusenc
  - libsamplerate
  - libtool
  - libunistring
  - libvdpau-va-gl
  - libxcrypt-compat
  - libxml2
  - libzip
  - lnav
  - lsof
  - lua
  - lzip
  - m4
  - make
  - man-db
  - man-pages
  - mdadm
  - mediainfo
  - mlocate
  - most
  - ncdu
  - ncurses
  - net-tools
  - nfs-utils
  - npm
  - numlockx
  - openssl
  - openssl-1.1
  - pacman
  - patch
  - pcsclite
  - pkgconf
  - poppler
  - python-i3ipc
  - python-pip
  - python-pymupdf
  - python-setuptools
  - qscintilla-qt5
  - r
  - ranger
  - ripgrep-all
  - rsync
  - rtirq
  - rtkit
  - ruby-bundler
  - rubygems
  - sed
  - smartmontools
  - sndio
  - sqlite
  - stunnel
  - sudo
  - suil
  - taglib
#  - timeshift
  - tesseract
  - texinfo
  - tuned
  - udisks2
  - usbutils
  - w3m
  - waf
  - wget
  - which
  - wol
  - xdg-user-dirs
  - xz
  - zlib
  # audio:
  # pipewire:
  # - pipewire-alsa
  # - pipewire-audio
  # - pipewire-jack
  # - pipewire-pulse
  # - wireplumber
  # alsa:
  - a2jmidid
  - alsa-lib
  - alsa-plugins
  - alsa-tools
  - alsa-utils
  # jack:
  - jack2
  - jack2-dbus
  - jack-example-tools
  - jack_capture
  - jack_utils
  # pulseaudio:
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - pulseaudio-jack
  - pulsemixer
  # ambisonics:
  - ambix-o1
  - ambix-o3
  - mcfx
  - sparta-plugins
  # applications:
  # - sonic-visualiser-git
  - raysession-git
  - ams
  - audacity
  #   - scala-music
  #   - scala-music-scales
#  - baudline-bin
  - carla
  - bipscript
  - bipscript-ide
  - ecasound
  - espeak-ng
  - fmit
  - gigedit
  #   - guitarix
  - gst-libav
  - gst-plugins-bad
  - helm-synth
  - hydrogen
  - jaaa
  - jack-keyboard
  - jack-rack
  - jack_mixer
  - jack_snapshot
  - jacktrip
  - jalv-select-git
  - japa
  - jconvolver
  - jkmeter
  - jmeters
  - jnoisemeter
  - ladspa
  - linuxsampler
  - lv2
  - lv2file
  - mixxx
  - moc
  - njconnect
  - non-sequencer
  - ocenaudio-bin
  - opus
  - opusfile
  - osc2midi
  - patchage
  - patchance
  - pavucontrol
  - polyphone
  - qmidiarp
  - qmidinet
  - qsampler
  - rtmidi
  - sendmidi
  - sfizz
  - sonic-pi-git
  - sonic-visualiser
  - sooperlooper-git
  #   - stochas
  #   - tonespace
  #   - vital-synth
  - sound-gambit
  - sox
  - spectmorph
  - timidity++
  - tuned
  - vamp-plugin-sdk
  - vmpk
  - vorbis-tools
  - wavpack
  - wolf-shaper
  - zita-ajbridge
  - zita-alsa-pcmi
  - zita-dpl1
  - zita-lrx
  - zita-mu1
  - zita-rev1
  # plugins:
  - ams-lv2
  - calf
  - caps-lv2-git
  - cmt
  - distrho-ports
  - dpf-plugins-vst3
  - dragonfly-reverb
  - iempluginsuite
  - intersect.lv2-git
  - ir.lv2
  - jalv-select-git
  - lsp-plugins
  - lv2-c++-tools
  - noise-repellent
  - swh-lv2-git
  - swh-plugins
  - tap-plugins-lv2-git
  - x42-plugins
  # workstation:
  # - antimicrox
  - asciiquarium
  - asp
  - aspell-en
  - barrier
  - darktable
  # - devdocs-desktop
  - epson-inkjet-printer-escpr2
  - figlet
  - feh
  - ffmpegthumbnailer
  # - gimp
  - github-cli
  - gitflow-avh
  - gitflow-zshcompletion-avh
  - gnuplot
  - google-chrome
  - gpick
  - grsync
  - gtksourceview3
  - gtksourceview4
  - gtkspell3
  - guake
  - hexchat
  - imv
  # - jgmenu-minimal
  - micro
  - mpv
  - mpv-plugin-excerpt-git
  # - musikcube
  - patat-bin
  - pdfjs
  - python-adblock
  - qutebrowser
  - redshift
  - seahorse
  - simplescreenrecorder
  - stunnel
  - sxiv
  - teiler-git
  - termdown
  - terminator
  - tilda
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - v4l2loopback-dkms
  - wmctrl
  # - wordnet-cli
  - xarchiver
  - xdot
  - xterm
  - xzgv
  - youtube-dl
  - zim
  # wm:
  - arandr
  - dunst
  - i3-wm
  - i3status-rust
  # - lightdm
  - nitrogen-git
  - perl-anyevent-i3
  - picom
  - rofi
  - sxhkd
  - wmfocus
  - xdot
  - xdotool
  - xf86-input-libinput
  - xf86-input-wacom
  - xf86-video-intel
  - xkill-shortcut
  - xorg-bdftopcf
  - xorg-fonts-alias-75dpi
  - xorg-fonts-alias-100dpi
  - xorg-fonts-alias-cyrillic
  - xorg-fonts-alias-misc
  - xorg-fonts-misc
  - xorg-iceauth
  - xorg-mkfontscale
  - xorg-server
  - xorg-sessreg
  - xorg-setxkbmap
  - xorg-smproxy
  - xorg-x11perf
  - xorg-xauth
  - xorg-xbacklight
  - xorg-xcmsdb
  - xorg-xcursorgen
  - xorg-xdpyinfo
  - xorg-xdriinfo
  - xorg-xev
  - xorg-xgamma
  - xorg-xhost
  - xorg-xinit
  - xorg-xinput
  - xorg-xkbcomp
  - xorg-xkbevd
  - xorg-xkbutils
  - xorg-xkill
  - xorg-xlsatoms
  - xorg-xlsclients
  - xorg-xlsfonts
  - xorg-xmodmap
  - xorg-xpr
  - xorg-xprop
  - xorg-xrandr
  - xorg-xrdb
  - xorg-xrefresh
  - xorg-xset
  - xorg-xsetroot
  - xorg-xvinfo
  - xorg-xwd
  - xorg-xwininfo
  - xorg-xwud
  # themes:
  - gtk-engines
  - gtk-engine-murrine
  # fonts:
  - gnu-free-fonts
  - ttf-devicons
  - ttf-font-awesome
  - ttf-icomoon-feather
  - ttf-input
  - ttf-jetbrains-mono
  - ttf-liberation
  - ttf-opensans
  - ttf-ubuntu-font-family
  # qt:
  - kvantum
  - qt5-base
  - qt5-graphicaleffects
  - qt5-quickcontrols2
  - qt5-tools
  - qt5ct
  - qt6-base
  - qt6-declarative
  - qt6-multimedia
  - qt6-tools
