---

- name: setup nas
  hosts: all
  gather_subset:
    - hardware
    - network

  vars_files:
    - "vars/{{ ansible_distribution }}.yml"

  vars:
    nfs:
      ports:
        lockd:
          tcp: 32803
          udp: 32769
        mountd: 892
        statd: 662
        rpc: 40418

  pre_tasks:

    - name: Include distro vars
      include_vars:
        file: vars/{{ ansible_distribution }}.yml
      tags: ['base']

  tasks:

    - import_role:
        name: network
      when: nas_host|bool

    - import_role:
        name: nginx
      when: web_host is defined

  post_tasks:

    - name: Reload firewalld
      shell: "firewall-cmd --reload"
      when: fw_nfs.changed
      ignore_errors: True
