---

- block:
    - name: create group for user
      group:
        name: "{{ user.group }}"
        state: present
        gid: "{{ user.gid }}"

    - name: add user to own group
      user:
        name: "{{ user.name }}"
        group: "{{ user.group }}"

  ignore_errors: "{{ ansible_check_mode }}"

- name: install yadm
  get_url:
    url: "https://github.com/TheLocehiliosan/yadm/raw/master/yadm"
    dest: "/usr/local/bin"
    mode: '0755'
  tags: ['yadm']

- name: copy clonedots script into user home
  copy:
    src: home/.local/bin/clonedots.sh
    dest: "{{ user.home }}/.local/bin/clonedots.sh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
  tags: ['yadm']

# - name: copy ssh keys from bender
#   copy:
#     src: "{{ user.home }}/.ssh/{{ item }}"
#     dest: "{{ user.home }}/.ssh/{{ item }}"
#     owner: "{{ user.name }}"
#     group: "{{ user.group }}"
#     mode: preserve
#     backup: yes
#   with_items:
#     - id_rsa
#     - id_rsa.pub
#   delegate_to: bender.syncopated.net
#   become_user: "{{ user.name }}"
#   tags: ['test']

# - name: clone, checkout and run yadm bootstrap
#   shell: echo "echo"
#
# - name: clone dots
#   script: "/usr/bin/uxterm -class 'backup' -e {{ user.home }}/.local/bin/yadm clone git@github.com:b08x/dots.git && sleep 2"
#   args:
#     chdir: "{{ user.home }}"
#   ignore_errors: True
#   tags: ['yadm']
#
# - name: bootstrap dots
#   script: "/usr/bin/uxterm -class 'backup' -e {{ user.home }}/.local/bin/yadm bootstrap && sleep 2"
#   args:
#     chdir: "{{ user.home }}"
#   tags: ['yadm']
