---

- name: Add user to groups defined in playbook
  user:
    name: "{{ user.name }}"
    groups: "{{ item }}"
    append: yes
  with_items:
    - audio
    - input
    - video
    - "{{ admin_group }}"

# to allow for ansible pipelining functionality
# https://docs.ansible.com/ansible/2.4/intro_configuration.html#pipelining
# while this requirement was removed in RHEL, many other distros leave this option enabled
- name: Disable requiretty for user so automation can run without interruption
  lineinfile:
    dest: /etc/sudoers
    regexp: "^Defaults    requiretty"
    line: "Defaults:{{ user.name }}    !requiretty"
    backrefs: yes
    backup: yes
    validate: 'visudo -cf %s'
