---

vars:
  user:
    name: aur_builder
    group: aur_builder
    uid: 1001
    gid: 1001
    home: /home/aur_builder
    shell: /usr/bin/zsh
    realname: Robert Pannick
    email: rwpannick@gmail.com
  workspace: /home/aur_builder/workspace
