---

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: True

- name: reload ufw
  ansible.builtin.systemd:
    name: ufw
    state: reloaded

- name: reload firewalld
  ansible.builtin.shell: |
    "firewall-cmd --reload"
  ignore_errors: True
