---

# - name: set jack engine parameters
#   shell: |
#    jack_control eps driver {{ jack.eps.driver }}
#   environment:
#     DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ user.uid }}/bus"
#   register: result
#   changed_when: result.rc != 0
#   become_user: "{{ user.name }}"
#
# - name: set jack driver parameters
#   shell: |
#     jack_control dps device {{ jack.dps.device }}
#     jack_control dps midi-driver {{ jack.dps.mididriver }}
#     jack_control dps monitor {{ jack.dps.monitor }}
#     jack_control dps period {{ jack.dps.period }}
#   environment:
#     DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ user.uid }}/bus"
#   register: result
#   changed_when: result.rc != 0
#   become_user: "{{ user.name }}"
