---

- name: ensure usr local directories exist
  file:
    path: "{{ item  }}"
    state: directory
    mode: '0755'
    recurse: False
  with_items:
    - "/usr/local/share/fonts/"
    - "/usr/local/share/icons"
    - "/usr/local/share/pixmaps/"
    - "/usr/local/share/themes"
    - "/usr/share/backgrounds/syncopated"
  tags: ['folders']

- block:
    - name: install input-remapper
      pip:
        name: git+https://github.com/sezanzeb/input-remapper.git
        extra_args: "--no-binary :all:"
        executable: pip3

    - name: enable input-remapper service
      systemd:
        name: input-remapper
        daemon_reload: yes
        enabled: True
        state: started

  ignore_errors: "{{ ansible_check_mode }}"

- name: set XDG env vars
  copy:
    content: |
      # -*- mode: shell-script -*-
      # ref: https://wiki.archlinux.org/title/XDG_Base_Directory
      ## XDG_RUNTIME_DIR defined by pam
      XDG_CONFIG_DIRS="/etc/xdg"
      XDG_DATA_DIRS="/usr/local/share/:/usr/share"
      XDG_CONFIG_HOME="$HOME/.config"
      XDG_CACHE_HOME="$HOME/.cache"
      XDG_DATA_HOME="$HOME/.local/share"
      XDG_STATE_HOME="$HOME/.local/state"
    dest: /usr/lib/environment.d/50-xdg-environment.conf
  tags: ['env', 'xdg']

- name: set environment vars
  template:
    src: etc/environment.j2
    dest: /etc/environment
    mode: '0644'
    backup: yes
  tags: ['env']

- name: install Thunar custom actions
  copy:
    src: "home/.config/Thunar/{{ item }}"
    dest: "{{ user.home }}/.config/Thunar/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
  with_items:
    - accels.scm
    - uca.xml
  tags: ['thunar']

- name: set thunar as default for opening directories
  shell: |
    xdg-mime default thunar.desktop inode/directory
  become_user: "{{ user.name }}"
  tags: ['thunar']

- include_tasks: theme.yml
  tags: ['theme']

- include_tasks: x11.yml
  tags: ['x11']
