---

distrib_id: Arch

autologin: False
shell_login: False

journal_level: notice

use_chaotic: False
use_cachy: False

kernel:
  mainline:
    - linux
    - linux-headers
    - dkms
  zen:
    - linux-zen
    - linux-zen-headers
    - dkms
  rt:
    - linux-rt-lts
    - linux-rt-lts-headers
    - dkms

gems:
  - activesupport
  - awesome_print
  - bcrypt_pbkdf
  - childprocess
  - clipboard
  - colorize
  - coltrane
  - ed25519
  - eventmachine
  - ffi
  - fractional
  - geo_coord
  - highline
  - i3ipc
  - i18n
  - kramdown
  - logging
  - minitest
  - mocha
  - multi_json
  - neovim
  - net-ssh
  - parallel
  - pastel
  - pry
  - pry-doc
  - rake
  - rdoc
  - rexml
  - rouge
  - ruby-openai
  - ruport
  - sync
  - sys-proctable
  - treetop
  - tty-box
  - tty-command
  - tty-prompt
  - tty-screen
  - yaml
