---

- name: Starting application tasks
  ansible.builtin.debug:
    msg: "starting application tasks"

- name: Copy raysession default scripts
  ansible.builtin.copy:
    src: "usr/local/share/raysession/session_templates/scripted/ray-scripts/{{ item }}"
    dest: "/usr/share/raysession/session_templates/scripted/ray-scripts/{{ item }}"
    mode: '0755'
    backup: yes
  loop:
    - close.sh
    - load.sh
    - save.sh
  tags: ['raysession']

- ansible.builtin.import_tasks:
    file: pulsar.yml
  when: install.pulsar|default(false)|bool == true
  tags: ['pulsar']

- ansible.builtin.import_tasks:
    file: vscode.yml
  when: install.vscode|default(false)|bool == true
  tags: ['vscode']

- ansible.builtin.import_tasks:
    file: vamp.yml
  tags: ['vamp']

- ansible.builtin.import_tasks:
    file: mixxx.yml
  tags: ['mixxx']

- name: Install vmpk keymap
  ansible.builtin.copy:
    src: usr/share/vmpk/qwerty_extended.xml
    dest: /usr/share/vmpk/qwerty_extended.xml
    mode: '0644'
  tags: ['vmpk']

- ansible.builtin.import_tasks:
    file: reaper.yml
  when: install_reaper|default(true)|bool == true
  tags: ['reaper']

- ansible.builtin.import_tasks:
    file: sonicannotator.yml
  when: install_annotator|default(true)|bool == true
  tags: ['sonicannotator']

- ansible.builtin.import_tasks:
    file: soniclineup.yml
  when: install_soniclineup|default(true)|bool == true
  tags: ['soniclineup']

- ansible.builtin.import_tasks:
    file: tony.yml
  when: install_tony|default(true)|bool == true
  tags: ['tony']

- ansible.builtin.import_tasks:
    file: touchosc.yml
  when: install_touchosc|default(true)|bool == true
  tags: ['touchosc']
