---

- name: starting application tasks
  debug:
    msg: "starting application tasks"

- name: copy raysession default scripts
  copy:
    src: "usr/local/share/raysession/session_templates/scripted/ray-scripts/{{ item }}"
    dest: "/usr/share/raysession/session_templates/scripted/ray-scripts/{{ item }}"
    mode: '0755'
    backup: yes
  with_items:
    - close.sh
    - load.sh
    - save.sh
  tags: ['raysession']

- include: pulsar.yml
  when: install_pulsar|default(false)|bool == true
  tags: ['pulsar']

- include: vamp.yml
  tags: ['vamp']

- include: mixxx.yml
  tags: ['mixxx']

- name: install vmpk keymap
  copy:
    src: usr/share/vmpk/qwerty_extended.xml
    dest: /usr/share/vmpk/qwerty_extended.xml
    mode: '0644'
  tags: ['vmpk']

- include: reaper.yml
  when: install_reaper|default(true)|bool == true
  tags: ['reaper']

- include: sonicannotator.yml
  when: install_annotator|default(true)|bool == true
  tags: ['sonicannotator']

- include: soniclineup.yml
  when: install_soniclineup|default(true)|bool == true
  tags: ['soniclineup']

- include: tony.yml
  when: install_tony|default(true)|bool == true
  tags: ['tony']

- include: touchosc.yml
  when: install_touchosc|default(true)|bool == true
  tags: ['touchosc']

# - include: baudline.yml
#   when: install_baudline|default(false)|bool == true
#   tags: ['baudline']
#
#
# - include: swami.yml
#   when: build_swami|default(false)|bool == true
#   tags: ['swami']
