---

- name: check if njconnect is already installed
  stat:
    path: /usr/local/bin/njconnect
  register: njconnect
  ignore_errors: "{{ ansible_check_mode }}"

- block:
    - name: install dependencies
      dnf:
        name: "{{ dependencies.Fedora }}"
        state: present
      when: ansible_distribution == 'Fedora'
      tags: ['packages']

    - name: install dependencies
      aur:
        use: auto
        name: "{{ dependencies.Archlinux }}"
        state: present
      when: ansible_distribution == 'Archlinux'
      become_user: aur_builder
      tags: ['packages']

    - name: clone njconnect
      git:
        repo: "https://github.com/radiganm/njconnect.git"
        dest: "/tmp/njconnect"
        accept_hostkey: yes
        update: no
        force: no

    - name: adjust Makefile to install to /usr/local
      shell: |
        sed -i 's/\/usr\/bin\/njconnect/\/usr\/local\/bin\/njconnect/g' Makefile
      args:
        chdir: /tmp/njconnect

    - name: make and install njconnect
      shell: |
        make && make install
      args:
        chdir: "/tmp/njconnect"

  when: not njconnect.stat.exists
  vars:
    dependencies:
      Fedora:
        - ncurses-devel
      Archlinux:
        - ncurses
