---

- name: check if reaper is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/reaper
  register: result
  ignore_errors: "{{ ansible_check_mode }}"

- name: check reaper version
  ansible.builtin.shell: |
    cat whatsnew.txt | grep {{ reaper.version }}
  args:
    chdir: /opt/REAPER
  register: if_installed_version
  changed_when: false
  failed_when: "'No such file or directory' not in if_installed_version.msg and if_installed_version.rc != 0"

- block:
    - name: fetch reaper
      ansible.builtin.get_url:
        url: "{{ reaper.url }}{{ reaper.file }}"
        dest: "/tmp"
        # validate_certs: no

    - name: uninstall reaper
      ansible.builtin.shell: |
        bash -x ./uninstall-reaper.sh --quiet --uninstall
      args:
        chdir: /opt/REAPER
      when: result.stat.exists

    - name: extract and install reaper
      ansible.builtin.shell: |
        tar -xvf {{ reaper.file }}

        cd reaper_linux_x86_64/

        ./install-reaper.sh --install /opt \
                        --integrate-desktop \
                        --usr-local-bin-symlink
      args:
        chdir: "/tmp"

  when: (not result.stat.exists or if_installed_version.changed)

- name: uninstall reaper only
  ansible.builtin.shell: |
    bash -x ./uninstall-reaper.sh --quiet --uninstall
  args:
    chdir: /opt/REAPER
  when: result.stat.exists and uninstall_reaper|default(false)|bool
