---

- name: check if sononym is installed
  stat:
    path: "/opt/sononym-1.4.2/sononym"
  register: result
  ignore_errors: "{{ ansible_check_mode }}"

- block:
    - name: fetch sononym
      get_url:
        url: https://www.sononym.net/download/sononym-1.4.2.tar.bz2
        dest: "/tmp/"

    - name: extract sononym to /opt
      unarchive:
        src: /tmp/sononym-1.4.2.tar.bz2
        dest: "/opt/"
        remote_src: yes

    - name: create sononym launcher
      lineinfile:
        path: /usr/local/bin/sononym
        line: |
          #!/usr/bin/env bash
          exec /opt/sononym-1.4.2/sononym
        create: yes
        mode: '0775'

  when: not result.stat.exists
