---

- name: Syncronize templates - shell
  ansible.builtin.template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/root' ]
    - [ '.aliases', '.profile', '.ualiases', '.zlogin', '.zprofile', '.zshenv', '.zshrc', '.zshrc.local' ]
  tags: ['shell', 'profile', 'alias' ]

- name: Synchronize templates - x11
  ansible.builtin.template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .Xresources
    - .xinitrc
    - .xprofile
    - .xserverrc
  register: x_config
  tags: ['x11', 'profile']

- name: Synchronize templates - wm
  ansible.builtin.template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/dunst/dunstrc
    - .config/i3/autostart
    - .config/i3/bindings
    - .config/i3/config
    - .config/i3/window_assignments
    - .config/i3status-rust/config.toml
    - .config/i3status-rust/themes/syncopated.toml
    - .config/picom/picom.conf
    - .config/sxhkd/sxhkdrc
  register: wmconfig
  tags: ['i3', 'dunst', 'picom', 'keybindings']

- name: Synchronize templates - terminal
  ansible.builtin.template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/alacritty/alacritty.yml
    - .config/kitty/cpu.conf
    - .config/kitty/current-theme.conf
    - .config/kitty/kitty.conf
    - .config/kitty/open-actions.conf
    - .config/kitty/start.conf
  tags: ['terminal', 'alacritty', 'kitty', 'tilda']

- name: Syncronize templates - gtk
  ansible.builtin.template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/root' ]
    - [ '.config/gtk-3.0/bookmarks', '.config/gtk-3.0/gtk.css', '.config/gtk-3.0/settings.ini', '.config/gtk-4.0/settings.ini', '.gtkrc-2.0' ]
  tags: ['gtk']

- name: Syncronize templates - qt
  ansible.builtin.template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/root' ]
    - [ '.config/Kvantum/kvantum.kvconfig', '.config/qt5ct/colors/syncopated.conf', '.config/qt5ct/qt5ct.conf', '.config/qt6ct/colors/syncopated.conf', '.config/qt6ct/qt6ct.conf' ]
  tags: ['qt']

- name: Synchronize templates - applications
  ansible.builtin.template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/htop/htoprc
    - .config/qutebrowser/autoconfig.yml
    - .config/qutebrowser/config.py
    - .config/qutebrowser/quickmarks
    - .config/zim/accelmap
    - .config/zim/preferences.conf
    - .config/zim/quicknote.conf
    - .config/zim/style.conf
    - .local/share/zim/templates/plugins/quicknote.txt
    - .sonic-pi/config/colour-theme.properties
  tags: ['htop', 'zim', 'qutebrowser', 'sonicpi', 'theme']

- name: Ensure .xinitrc is executable
  ansible.builtin.file:
    path: "{{ user.home }}/.xinitrc"
    mode: '0755'
  when: x_config.changed
  tags: ['x11', 'profile']

- name: Ensure root home is owned by root
  ansible.builtin.file:
    path: /root/
    owner: root
    group: root
    recurse: True

- name: Reload i3
  ansible.builtin.command: bash -lc "i3-msg -s /run/user/{{ user.uid }}/i3/ipc-socket.* reload"
  become_user: "{{ user.name }}"
  when: wmconfig.changed
  ignore_errors: True
  tags: ['i3', 'dunst', 'picom', 'keybindings', 'sxhkd']
