---

- name: Collect only selected facts
  ansible.builtin.setup:
    filter:
      - 'ansible_processor'

- name: install i3autolayout.py
  ansible.builtin.copy:
    src: home/.local/bin/i3autolayout.py
    dest: "{{ user.home }}/.local/bin/i3autolayout.py"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'

# - import_tasks: skel.yml
#   when: build_iso is defined
#   tags: ['iso']

- ansible.builtin.import_tasks:
    file: home.yml
  tags: ['home']

- ansible.builtin.import_tasks:
    file: x11.yml
  tags: ['x11']

- ansible.builtin.import_tasks:
    file: theme.yml
  tags: ['theme']

- ansible.builtin.import_tasks:
    file: xdg.yml
  tags: ['xdg']

- ansible.builtin.import_tasks:
    file: menu.yml
  tags: ['menu']

- ansible.builtin.import_tasks:
    file: input-remapper.yml
  tags: ['input-remapper']

- name: Set XDG env vars
  ansible.builtin.copy:
    content: |
      # -*- mode: shell-script -*-
      # ref: https://wiki.archlinux.org/title/XDG_Base_Directory
      ## XDG_RUNTIME_DIR defined by pam
      XDG_CONFIG_DIRS="/etc/xdg"
      XDG_DATA_DIRS="/usr/local/share/:/usr/share"
      XDG_CONFIG_HOME="$HOME/.config"
      XDG_CACHE_HOME="$HOME/.cache"
      XDG_DATA_HOME="$HOME/.local/share"
      XDG_STATE_HOME="$HOME/.local/state"
    dest: /usr/lib/environment.d/50-xdg-environment.conf
  tags: ['env', 'xdg']

- name: Set misc profile vars
  ansible.builtin.template:
    src: usr/lib/environment.d/51-misc-environment.conf.j2
    dest: /usr/lib/environment.d/51-misc-environment.conf
    mode: '0644'
    backup: yes
  tags: ['env']

- name: Install Thunar actions
  ansible.builtin.copy:
    src: "files/etc/xdg/Thunar/{{ item }}"
    dest: "/etc/xdg/Thunar/{{ item }}"
    mode: '0644'
  with_items:
    - accels.scm
    - uca.xml
  tags: ['thunar']

- name: Set Thunar as default for opening directories
  ansible.builtin.shell: xdg-mime default thunar.desktop inode/directory
  become_user: "{{ user.name }}"
  tags: ['thunar']
