---

- include_vars:
    dir: "{{ lookup('env','ANSIBLE_HOME') }}/roles/ui/defaults/"
    extensions:
      - 'yml'

- name: ensure these directories exist
  file:
    path: "{{ user.home }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
    recurse: False
  with_items:
    - .config/Debauchee
    - .config/Kvantum
    - .config/Thunar
    - .config/alacritty
    - .config/dunst
    - .config/gtk-3.0
    - .config/gtk-4.0
    - .config/htop
    - .config/i3
    - .config/i3status-rust/themes/
    - .config/kitty
    - .config/nitrogen
    - .config/picom
    - .config/qt5ct/colors
    - .config/qt6ct/colors
    - .config/qutebrowser
    - .config/sxhkd
    - .config/tilda
    - .config/zim
    - .local/share/zim/templates/plugins
    - .guake
    - .sonic-pi/config

- name: syncronize templates - wm
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/dunst/dunstrc
    - .config/i3/autostart
    - .config/i3/config
    - .config/i3/window_assignments
    - .config/i3status-rust/config.toml
    - .config/i3status-rust/themes/syncopated.toml
    - .config/picom/picom.conf
  notify: reload i3
  tags: ['i3', 'dunst']

- name: syncronize templates - x
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .Xresources
    - .xinitrc
    - .xprofile
    - .xserverrc
  tags: ['x', 'profile']

- name: ensure .xinitrc is executable
  file:
    path: "{{ user.home }}/.xinitrc"
    mode: '0755'
  tags: ['x', 'profile']

- name: syncronize templates - shell
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .aliases
    - .profile
    - .ualiases
    - .zlogin
    - .zprofile
    - .zshenv
    - .zshrc
    - .zshrc.local
  tags: ['zsh', 'shell', 'profile']

- name: syncronize templates - gtk
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/gtk-3.0/bookmarks
    - .config/gtk-3.0/gtk.css
    - .config/gtk-3.0/settings.ini
    - .config/gtk-4.0/settings.ini
    - .gtkrc-2.0
  tags: ['gtk']

- name: syncronize templates - qt
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/Kvantum/kvantum.kvconfig
    - .config/qt5ct/colors/syncopated.conf
    - .config/qt5ct/qt5ct.conf
    - .config/qt6ct/colors/syncopated.conf
    - .config/qt6ct/qt6ct.conf
  tags: ['qt']

- name: syncronize templates - terminal
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/alacritty/alacritty.yml
    - .config/kitty/cpu.conf
    - .config/kitty/current-theme.conf
    - .config/kitty/kitty.conf
    - .config/kitty/open-actions.conf
    - .config/kitty/start.conf
#    - .config/tilda/config_0
#    - .config/tilda/config_1
  tags: ['terminal', 'alacritty', 'kitty', 'tilda']

- name: syncronize templates - applications
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/htop/htoprc
    - .config/qutebrowser/autoconfig.yml
    - .config/qutebrowser/config.py
    - .config/qutebrowser/quickmarks
    - .config/zim/accelmap
    - .config/zim/notebooks.list
    - .config/zim/preferences.conf
    - .config/zim/quicknote.conf
    - .config/zim/style.conf
    - .local/share/zim/templates/plugins/quicknote.txt
    - .sonic-pi/config/colour-theme.properties
  tags: ['applications', 'htop', 'zim', 'qutebrowser', 'sonicpi']

- name: syncronize templates - keybindings
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - .config/i3/bindings
    - .config/sxhkd/sxhkdrc
  notify: reload i3
  tags: ['keybindings', 'i3', 'sxhkd']
