---

kernel:
  - linux-rt-lts
  - linux-rt-lts-headers
  - dkms
networkmanager:
  - network-manager-applet
  - networkmanager
  - nm-connection-editor
bluetooth:
  - bluez-utils
  - bluetooth-autoconnect
system:
  # - lightdm
  - aria2
  - aribb24
  - atool
  - autoconf
  - autofs
  - autojump
  - automake
  - base-devel
  - bat
  - bc
  - bibtool
  - bind
  - binutils
  - bison
  - bluez-utils
  - boost
  - brightnessctl
  - ccache
  - cmake
  - cppunit
  - cpupower
  - dialog
  - dmidecode
  - exa
  - faad2
  - fakeroot
  - fasd
  - fd
  - file
  - findutils
  - firewalld
  - flex
  - fwupd
  - fzf
  - gawk
  - gcc
  - gcc-libs
  - gendesk
  - gettext
  - git
  - git-filter-repo
  - git-lfs
  - glibc
  - glow
  - gnu-netcat
  - graphicsmagick
  - grep
  - groff
  - gtkmm
  - gum
  - gzip
  - help2man
  - htop
  - hunspell
  - iftop
  - imlib2
  - inetutils
  - iotop
  - jansson
  - jq
  - kitty
  - kitty-terminfo
  - libbluray
  - libev
  - libgit2
  - libgme
  - libmad
  - libnm
  - libnma
  - libopusenc
  - libsamplerate
  - libtool
  - libunistring
  - libvdpau-va-gl
  - libxcrypt-compat
  - libxml2
  - libzip
  - lnav
  - lsof
  - lua
  - lzip
  - m4
  - make
  - man-db
  - man-pages
  - mdadm
  - mediainfo
  - mlocate
  - most
  - ncdu
  - ncurses
  - net-tools
  - nfs-utils
  - npm
  - numlockx
  - openssl
  - openssl-1.1
  - pacman
  - pandoc
  - patch
  - pcsclite
  - pkgconf
  - poppler
  - python-i3ipc
  - python-pip
  - python-pymupdf
  - python-setuptools
  - r
  - ranger
  - ripgrep-all
  - rsync
  - rtirq
  - rtkit
  - ruby-bundler
  - rubygems
  - sed
  - smartmontools
  - sndio
  - sqlite
  - stunnel
  - sudo
  - suil
  - taglib
  - tesseract
  - texinfo
  - timeshift
  - tuned
  - udisks2
  - usbutils
  - w3m
  - waf
  - wget
  - which
  - wol
  - xdg-user-dirs
  - xz
  - zlib
