---

- name: Starting network tasks
  ansible.builtin.debug:
    msg: "Starting network tasks"

- ansible.builtin.import_tasks:
    file: networkmanager.yml
  tags: ['networkmanager']

- ansible.builtin.import_tasks:
    file: autofs.yml
  when: autofs_client is defined
  tags: ['autofs']

- ansible.builtin.import_tasks:
    file: nas/nfs.yml
  when: nfs_host|bool
  tags: ['nfs']

- ansible.builtin.import_tasks:
    file: nas/rsyncd.yml
  when: rsyncd_host|bool
  tags: ['rsyncd']

- ansible.builtin.import_tasks:
    file: nas/musikcube.yml
  when: musikcube_host|bool
  tags: ['musikcube']

#TODO: add task file
# - ansible.builtin.import_tasks:
#     file: syncthing.yml
#   when: syncthing_client|bool
#   tags: ['syncthing']
