---

- name: starting network tasks
  debug:
    msg: "Starting network tasks"

- include_tasks: networkmanager.yml
  tags: ['networkmanager']

- include_tasks: firewall.yml
  tags: ['firewall']

- include_tasks: autofs.yml
  when: autofs_client is defined
  tags: ['network']
