---

- name: starting network tasks
  debug:
    msg: "Starting network tasks"

- include: networkmanager.yml
  tags: ['networkmanager']

- include: autofs.yml
  when: autofs_client is defined
  tags: ['network']
