---

- name: Starting audio role tasks
  ansible.builtin.debug:
    msg: "Starting audio tasks"

- name: Add modprobe for alsa card order
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/10-alsa_usb.conf
    line: "options snd slots=snd-hda-intel,snd-usb-audio"
    create: yes
    backup: yes
  tags: ['modprobe']

- ansible.builtin.import_tasks:
    file: tuning.yml
  tags: ['tuning']

- ansible.builtin.import_tasks:
    file: jack.yml
  tags: ['jack']

- ansible.builtin.import_tasks:
    file: pulseaudio.yml
  tags: ['pulseaudio']
