---

- name: Update pulseaudio configs
  ansible.builtin.copy:
    src: "etc/pulse/{{ item }}"
    dest: "{{ user.home }}/.config/pulse/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_items:
    - client.conf
    - daemon.conf
    - default.pa
    - system.pa

- block:
    - name: install bluetooth packages
      aur:
        use: auto
        name: "{{ item }}"
        state: present
      with_items:
        - bluetooth-autoconnect
        - bluez
        - bluez-utils
        - pulseaudio-bluetooth
      become: False
      become_user: "{{ user.name }}"

    - name: Install pulseaudio bluetooth config
      ansible.builtin.copy:
        src: etc/pulse/default.pa.d/bluetooth.pa
        dest: /etc/pulse/default.pa.d/bluetooth.pa
        mode: '0644'

  when: use_bluetooth|bool
  notify: restart pulseaudio
  tags: ['bluetooth']

- name: Adjust pulseaudio.service file
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/user/pulseaudio.service
    insertafter: '^Description'
    line: 'After=jack_control.service'
    backup: yes

# - name: enable pulseaudio service
#   systemd:
#     name: "{{ item }}"
#     enabled: yes
#     scope: user
#   with_items:
#     - pulseaudio.service
#     - pulseaudio.socket
#   environment:
#     XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
#   become_user: "{{ user.name }}"
