- name: starting docker tasks
  debug:
    msg: "Starting docker tasks"

- name: install docker packages
  aur:
    use: auto
    name: "{{ docker.packages }}"
    state: present
  become_user: "{{ user.name }}"
  notify: docker service
  tags: ['packages']

- name: add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  check_mode: no
  ignore_errors: yes

- name: set docker storage location
  lineinfile:
    path: "/usr/lib/systemd/system/docker.service"
    regexp: "^ExecStart=/usr/bin/dockerd -H fd://"
    line: "ExecStart=/usr/bin/dockerd --data-root {{ docker.storage }} -H fd:// --containerd=/run/containerd/containerd.sock"
  notify: reload systemd daemon

- name: create docker config directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: enable experimental features in docker
  copy:
    content: |
      {
        "experimental": true
      }

    dest: "/etc/docker/daemon.json"
    owner: root

- name: disable overlay redirect
  copy:
    content: |
      options overlay metacopy=off redirect_dir=off

    dest: "/etc/modprobe.d/disable-overlay-redirect-dir.conf"
    owner: root
