- name: Starting docker tasks
  ansible.builtin.debug:
    msg: "Starting docker tasks"

- name: Install docker packages
  aur:
    use: auto
    name: "{{ docker.packages }}"
    state: present
  become_user: "{{ user.name }}"
  notify: docker service
  tags: ['packages']

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  check_mode: no
  ignore_errors: yes

- name: Set docker storage location
  ansible.builtin.lineinfile:
    path: "/usr/lib/systemd/system/docker.service"
    regexp: "^ExecStart=/usr/bin/dockerd -H fd://"
    line: "ExecStart=/usr/bin/dockerd --data-root {{ docker.storage }} -H fd:// --containerd=/run/containerd/containerd.sock"
  notify: reload systemd daemon

- name: Create docker config directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Enable experimental features in docker
  ansible.builtin.copy:
    content: |
      {
        "experimental": true
      }

    dest: "/etc/docker/daemon.json"
    owner: root

- name: Disable overlay redirect
  ansible.builtin.copy:
    content: |
      options overlay metacopy=off redirect_dir=off

    dest: "/etc/modprobe.d/disable-overlay-redirect-dir.conf"
    owner: root

# Reset is not implemented local connection
- name: Reboot host
  ansible.builtin.reboot:
  async: 1
  poll: 0
  ignore_errors: True
  when: reboot is defined

- name: Wait for host to reboot
  ansible.builtin.wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 120
  when: reboot is defined
