---

- name: Starting libvirt tasks
  ansible.builtin.debug:
    msg: "Starting libvirt tasks"

# :: exfatprogs and exfat-utils are in conflict. Remove exfat-utils? [y/N]
- name: Remove conflicting packages
  community.general.pacman:
    name: exfat-utils
    state: absent
    force: yes
    extra_args: --noconfirm
  tags: ['packages']

- name: Install qemu package
  ansible.builtin.shell: |
    if [ {{ install.libvirt.qemu_full }} == 'True' ];then
      yes | pacman -S qemu-full
    else
      yes | pacman -S qemu-base
    fi
  tags: ['packages']

- name: Install libvirt packages
  community.general.pacman:
    name: "{{ libvirt.packages }}"
    state: present
    force: yes
    extra_args: --noconfirm
  tags: ['packages']

- block:
    - name: Set socket group and perms to allow for remote access
      ansible.builtin.copy:
        src: etc/libvirt/libvirtd.conf
        dest: /etc/libvirt/libvirtd.conf
        mode: '0644'

    - name: Disable lvmetad for remote access reasons
      ansible.builtin.lineinfile:
        dest: /etc/lvm/lvm.conf
        regexp: "^    use_lvmetad = 1"
        line: "    use_lvmetad = 0"
        backrefs: yes
        backup: yes

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ user.name }}"
        groups: "libvirt,kvm"
        append: yes
      ignore_errors: "{{ ansible_check_mode }}"

  notify: "libvirtd service"
