---

- ansible.builtin.include_tasks:
    file: docker.yml
  when: install.docker|default(false)|bool == True
  tags: ['docker']

- ansible.builtin.include_tasks:
    file: libvirt.yml
  when: install.libvirt|default(false)|bool == True
  tags: ['libvirt']
