---

- ansible.builtin.include_tasks:
    file: docker.yml
  when: install.docker is defined
  tags: ['docker']

- ansible.builtin.include_tasks:
    file: libvirt.yml
  when: install.libvirt is defined
  tags: ['libvirt']
