---

- ansible.builtin.include_tasks:
    file: docker.yml
  when: install.docker|bool
  tags: ['docker']

- ansible.builtin.include_tasks:
    file: libvirt.yml
  when: install.libvirt|bool
  tags: ['libvirt']
