---

- name: restart nginx
  ansible.builtin.debug:
    msg: checking config first
  changed_when: True
  notify:
    - check nginx configuration
    - restart nginx - after config check

- name: reload nginx
  ansible.builtin.debug:
    msg: checking config first
  changed_when: True
  notify:
    - check nginx configuration
    - reload nginx - after config check

- name: reload nginx - without service
  ansible.builtin.shell: "{{ nginx_binary_name }} -s reload"
  register: result
  changed_when: "result.rc != 0"

- name: check nginx configuration
  ansible.builtin.shell: "{{ nginx_binary_name }} -t"
  register: result
  changed_when: "result.rc != 0"
  when: nginx_installation_type in nginx_installation_types_using_service

- name: restart nginx - after config check
  ansible.builtin.service: name={{ nginx_service_name }} state=restarted
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"

- name: reload nginx - after config check
  ansible.builtin.service: name={{ nginx_service_name }} state=reloaded
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
