---

- name: install devtools
  aur:
    use: auto
    name: devtools
    state: present
  become_user: aur_builder

- name: ensure folder tree
  file:
    path: "/home/aur_builder/{{ item }}"
    state: directory
    owner: aur_builder
    group: aur_builder
  with_items:
    - Packages
    - Packages/x86_64
    - Packages/x86_64/sources
    - Packages/x86_64/srcpackages
    - Packages/x86_64/makepkglogs
    - Packages/x86_64_v3
    - Packages/x86_64_v3/sources
    - Packages/x86_64_v3/srcpackages
    - Packages/x86_64_v3/makepkglogs
    - Repository
    - Repository/x86_64
    - Repository/x86_64_v3
    - Workspace
  become_user: aur_builder

- name: sync devtools and pkgbuilds folder
  synchronize:
    src: "files/{{ item }}"
    dest: "/home/aur_builder/Workspace/"
    recursive: yes
    mode: push
    delete: yes
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
  with_items:
    - devtools
    - pkgbuilds
  tags: ['devtools', 'pkgbuilds']

- name: copy makepkg and pacman templates to workspace
  template:
    src: "devtools/{{ item }}.j2"
    dest: "/home/aur_builder/Workspace/devtools/{{ item }}"
    owner: aur_builder
    group: aur_builder
    mode: '0644'
  with_items:
    - makepkg-x86_64.conf
    - makepkg-x86_64_v3.conf
    - pacman-x86_64.conf
    - pacman-x86_64_v3.conf
  tags: ['devtools']

- name: ensure group writeable for aur_builder home
  file:
    path: /home/aur_builder/Workspace
    state: directory
    owner: aur_builder
    group: aur_builder
    mode: '0775'
    recurse: True
