---

- name: install devtools
  aur:
    use: auto
    name: devtools
    state: present
  become_user: aur_builder

- name: ensure folder tree
  file:
    path: "/home/aur_builder/{{ item }}"
    state: directory
    owner: aur_builder
    group: aur_builder
  with_items:
    - Packages
    - Packages/x86_64
    - Packages/x86_64_v3
    - Repository
    - Repository/x86_64
    - Repository/x86_64_v3
    - Workspace
  become_user: aur_builder

- name: sync devtools and pkgbuilds folder
  synchronize:
    src: "files/{{ item }}"
    dest: "/home/aur_builder/Workspace/{{ item }}/"
    recursive: yes
    mode: push
    delete: no
    checksum: yes
    perms: no
    rsync_opts:
      - "--update"
      - "--omit-dir-times"
  with_items:
    - devtools
    - pkgbuilds

- name: copy makepkg and pacman templates to workspace
  template:
    src: "devtools/{{ item }}.j2"
    dest: "/home/aur_builder/Workspace/devtools/{{ item }}"
    owner: aur_builder
    group: aur_builder
    mode: '0644'
  with_items:
    - makepkg-x86_64.conf
    - makepkg-x86_64_v3.conf
    - pacman-x86_64.conf
    - pacman-x86_64_v3.conf
