---

login:
  auto: False
  shell: False
  lightdm: False

nvidia: True

repo:
  cachy: True
  chaotic: False

kernel:
  zen: False
  rt: False

install:
  docker: True
  pulsar: True
  vscode: False

ohmyzsh:
  theme: kphoen

devices:
  dicatphone_powermicII: "Dictaphone Corporation PowerMicII-NS"
  logitech_mouse_g403: "Logitech G403 HERO Gaming Mouse"
  daskeyboard: "daskeyboard"

i3:
  autostart:
    - "jacktrip -s -n 4 -q auto -b 24 -D --udprt"
    - "/usr/bin/barriers -f --debug INFO --name ninjabot --disable-crypto --disable-client-cert-checking -c ~/.config/Debauchee/ninjabot.conf --address :24800"
    # - "/usr/bin/barrierc -f --no-tray --debug INFO --name ninjabot --disable-crypto [soundbot]:24800"
    - "terminator"
    - "pulsar;sleep 2"
    - "obsidian;sleep 2"
    - 'jack_load "deskmic" zalsa_in -i "-d hw:3,0"'
    # - "hexchat --minimize=2"
  tray_output: "DVI-I-1"
  assignments:
    - '[class="Jalv.gtk" title="Helm"] $ws6'
    - '[class="qmidiarp"] $ws6'
  workspaces:
    - "$ws1 output DVI-D-0"
    - "$ws2 output DVI-D-0"
    - "$ws3 output DVI-D-0"
    - "$ws4 output DVI-D-0"
    - "$ws5 output DVI-D-0"
    - "$ws6 output DVI-I-1"
    - "$ws7 output DVI-I-1"
    - "$ws8 output DVI-I-1"
    - "$ws9 output DVI-I-1"
    - "$ws10 output DVI-I-1"
