---

install:
  docker: True
  libvirt:
    qemu_full: True
  pulsar: True

ohmyzsh:
  theme: kphoen

nas_host: True
nfs_host: True

use_bluetooth: True

i3:
  autostart:
    - "jacktrip -c ninjabot -n 4 -q auto -b 24 -D --udprt"
    - "/usr/bin/barrierc -f --debug INFO --name soundbot --disable-crypto [ninjabot]:24800"
    # - "/usr/bin/barriers -f --debug INFO --name soundbot --disable-crypto --disable-client-cert-checking -c ~/.config/Debauchee/soundbot.conf --address :24800"
    - "terminator"
  tray_output: "primary"
  assignments:
    - '[class="Jalv.gtk" title="Helm"] $ws8'
    - '[class="qmidiarp"] $ws8'
    - '[class="Qsampler"] $ws9'
    - '[class="^Patchage"] $ws9'
    - '[class="Jalv.select"] $ws9'
    - '[class="^RaySession$"] $ws9'
  workspaces:
    - "$ws1 output eDP1"
    - "$ws2 output HDMI1"
    - "$ws3 output HDMI1"
    - "$ws4 output HDMI1"
    - "$ws5 output HDMI1"
    - "$ws6 output HDMI1"
    - "$ws7 output HDMI1"
    - "$ws8 output HDMI1"
    - "$ws9 output HDMI1"
    - "$ws10 output HDMI1"
