---

- import_tasks: user.yml
  tags: ['user']

- import_tasks: create-dirs.yml

- name: install sshd config
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: True
  notify: restart sshd
  tags: ['sshd']

- name: Include distro vars
  include_vars:
    file: vars/{{ ansible_distribution }}.yml

- name: install sshd config
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: True
  notify: restart sshd
  tags: ['sshd']

- import_tasks: zshell.yml
  tags: ['zsh']

- import_tasks: firewall.yml
  tags: ['firewall']

- import_tasks: filesystem.yml
  tags: ['filesystem']

- import_tasks: utils.yml
  tags: ['utils']

- import_tasks: updatedb.yml
  tags: ['updatedb']

- import_tasks: autologin.yml
  when: autologin|bool
  tags: ['autologin']

- import_tasks: nvidia.yml
  when: use_nvidia|default(false)|bool == true
  tags: ['nvidia']

- import_tasks: grub.yml
  tags: ['grub']
