---

- ansible.builtin.import_tasks:
    file: ruby.yml
  tags: ['ruby']

- name: Include tasks based on distribution
  ansible.builtin.include_tasks: "distro/{{ ansible_distribution }}.yml"
  tags: ['packages', 'mirrors']

- name: Include distro vars
  ansible.builtin.include_vars:
    file: vars/{{ ansible_distribution }}.yml

- name: install sshd config
  ansible.builtin.template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: True
  notify: restart sshd
  tags: ['sshd']

- ansible.builtin.import_tasks:
    file: zshell.yml
  tags: ['zsh']

- ansible.builtin.import_tasks:
    file: firewall.yml
  tags: ['firewall']

- ansible.builtin.import_tasks:
    file: filesystem.yml
  tags: ['filesystem']

- ansible.builtin.import_tasks:
    file: utils.yml
  tags: ['utils']

- ansible.builtin.import_tasks:
    file: updatedb.yml
  tags: ['updatedb']

- ansible.builtin.import_tasks:
    file: autologin.yml
  when: login.auto|bool
  tags: ['autologin']

- ansible.builtin.import_tasks:
    file: nvidia.yml
  when: nvidia|default(false)|bool == True
  tags: ['nvidia']

- ansible.builtin.import_tasks:
    file: grub.yml
  tags: ['grub']

- ansible.builtin.import_tasks:
    file: syncthing.yml
  when: install.syncthing|bool
  tags: ['syncthing']
