---

- block:
    - name: install nvidia drivers
      aur:
        use: paru
        name: "{{ item }}"
        state: present
      with_items:
        - nvidia-470xx-dkms
        - nvidia-470xx-settings
        - nvidia-470xx-utils
      become: True
      become_user: "{{ user.name }}"

    - name: install xorg.conf for nvidia
      copy:
        src: etc/X11/xorg.conf.d/20-nvidia.conf
        dest: /etc/X11/xorg.conf.d/20-nvidia.conf
        mode: '0644'

    - name: install modprobe configurations
      copy:
        src: "etc/modprobe.d/{{ item }}"
        dest: "/etc/modprobe.d/{{ item }}"
        mode: '0644'
      with_items:
        - blacklist_nouveau.conf
        - nvidia.conf

  when: ansible_distribution == 'Archlinux'
