---
#FIXME: For some reason, some gems were installed to /root/.local/....
# removing /etc/gemrc and ~/.gemrc allowed for gems to be install to ~/.local
# not sure why

- name: remove gemrc configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ user.home }}/.gemrc"
    - /etc/gemrc

- block:
    - name: checking test
      debug:
        msg: "heyo!"

    - name: check if rvm is install
      ansible.builtin.shell: rvm version
      register: rvm_installed

    - name: install rvm and ruby 3
      ansible.builtin.shell: |
        gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

        \curl -sSL https://get.rvm.io | bash -s stable

        source $HOME/.rvm/scripts/rvm

        rvm pkg install openssl

        rvm install 3.0.0 --with-openssl-dir=$HOME/.rvm/usr

        rvm install 3.2.0

        rvm use 3.2.0 && rvm gemset use global && gem install pry pry-doc logging openai

        rvm --default use 3.2.0
      args:
        chdir: "{{ user.home }}"
      when: rvm_installed.rc != 0

    #FIXME: RVM is not a function, selecting rubies with 'rvm use ...' will not work.


    # - name: Gather list of installed gems
    #   ansible.builtin.shell: |
    #     source $HOME/.rvm/scripts/rvm && \
    #     rvm gemset use global && gem list | awk '{ print $1 }'
    #   args:
    #     chdir: "{{ user.home }}"
    #   register: gemlist
    #   changed_when: gemlist.rc != 0
    #   ignore_errors: "{{ ansible_check_mode }}"
    #
    # - name: Set list of gems to install
    #   ansible.builtin.set_fact:
    #     _gems: "{{ gems|difference(gemlist.stdout) }}"
    #
    # - name: install ruby gems
    #   shell: |
    #     source $HOME/.rvm/scripts/rvm && \
    #     rvm gemset use global && gem install {{ item }}
    #   args:
    #     chdir: "{{ user.home }}"
    #   loop:
    #     - "{{ _gems }}"

  when: install.rvm|default(false)|bool == True
  become_user: "{{ user.name }}"
  tags: ['rvm']
