---
#FIXME: For some reason, some gems were installed to /root/.local/....
# removing /etc/gemrc and ~/.gemrc allowed for gems to be install to ~/.local
# not sure why

- name: remove gemrc configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ user.home }}/.gemrc"
    - /etc/gemrc

- name: Gather list of installed gems
  ansible.builtin.shell: "gem list | awk '{ print $1 }'"
  register: gemlist
  changed_when: gemlist.rc != 0
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set list of gems to install
  ansible.builtin.set_fact:
    _gems: "{{ gems|difference(gemlist.stdout) }}"

- name: Install ruby gems
  ansible.builtin.shell: "gem install {{ item }}"
  with_items:
    - "{{ _gems }}"
  when: _gems | length > 0

#TODO: check if rvm and rubies are already installed
- block:
    - name: checking test
      debug:
        msg: "heyo!"
    # - name: install rvm and ruby 3
    #   ansible.builtin.shell: |
    #     gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    #
    #     \curl -sSL https://get.rvm.io | bash -s stable
    #
    #     source /home/b08x/.rvm/scripts/rvm
    #
    #     rvm pkg install openssl
    #
    #     rvm install 3.0.0 --with-openssl-dir=$HOME/.rvm/usr
    #
    #     rvm install 3.2.0

    #     rvm use 3.2.0 && rvm gemset global && gem install pry pry-doc logging openai
    #
    #     rvm 1.9.2 --default
    #   args:
    #     chdir: "{{ user.home }}"

  when: install.rvm|default(false)|bool == True
  become: False
  tags: ['rvm']

#TODO: add shell configurations based on conditional

#
#
# TASK [system : Syncronize templates - shell] ********************************************************************************************************************************
# ok: [lapbot] => (item=['/home/b08x', '.aliases'])
# --- before: /home/b08x/.profile
# +++ after: /tmp/ansible-local-33217cieosbfq/tmparef0h5b/.profile.j2
# @@ -39,8 +39,3 @@
#  if [ -x $(command -v hostname) ]; then
#  export HOSTNAME=$(hostname)
#  fi
# -
# -# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
# -export PATH="$PATH:$HOME/.rvm/bin"
# -
# -[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
#
# changed: [lapbot] => (item=['/home/b08x', '.profile'])
# ok: [lapbot] => (item=['/home/b08x', '.ualiases'])
# --- before: /home/b08x/.zlogin
# +++ after: /tmp/ansible-local-33217cieosbfq/tmpw6xm0rcq/.zlogin.j2
# @@ -1,2 +0,0 @@
# -
# -[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
#
# changed: [lapbot] => (item=['/home/b08x', '.zlogin'])
# ok: [lapbot] => (item=['/home/b08x', '.zprofile'])
# ok: [lapbot] => (item=['/home/b08x', '.zshenv'])
# --- before: /home/b08x/.zshrc
# +++ after: /tmp/ansible-local-33217cieosbfq/tmp3ra2zvfh/.zshrc.j2
# @@ -104,6 +104,3 @@
#
#  # additional aliases
#  [[ -f ~/.ualiases ]] && source ~/.ualiases
# -
# -# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
# -export PATH="$PATH:$HOME/.rvm/bin"
