---
#FIXME: For some reason, some gems were installed to /root/.local/....
# removing /etc/gemrc and ~/.gemrc allowed for gems to be install to ~/.local
# not sure why

- name: remove gemrc configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ user.home }}/.gemrc"
    - /etc/gemrc

- name: Gather list of installed gems
  ansible.builtin.shell: "gem list | awk '{ print $1 }'"
  register: gemlist
  changed_when: gemlist.rc != 0
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set list of gems to install
  ansible.builtin.set_fact:
    _gems: "{{ gems|difference(gemlist.stdout) }}"

- name: Install ruby gems
  ansible.builtin.shell: "gem install {{ item }}"
  with_items:
    - "{{ _gems }}"
  when: _gems | length > 0
