---

- name: Add to RobotStuff to PATH
  copy:
    content: "export PATH=$PATH:{{ user.home }}/RobotStuff/bin"
    dest: "/etc/profile.d/RobotStuff.sh"
    mode: '0755'

- block:
    - name: clone RobotStuff repository
      git:
        repo: "https://github.com/b08x/RobotStuff.git"
        dest: "{{ user.home }}/RobotStuff"
        recursive: yes
        accept_hostkey: yes
        update: no
        force: no
      check_mode: no

    - name: Ensure files in RobotStuff/bin are executable
      ansible.builtin.file:
        path: "{{ user.home }}/RobotStuff/bin"
        mode: '0755'
        recurse: True

  become_user: "{{ user.name }}"
