---

- include: musikcube.yml
  when: musikcube_host is defined
  tags: ['musikcube']

- include: nfs.yml
  when: nfs_host is defined
  tags: ['nfs']

- include: rsyncd.yml
  when: rsyncd_host is defined
  tags: ['rsyncd']

- import_role:
    name: nginx
  when: web_host is defined
