---

autofs_client:
  host: bender
  shares:
    - Archive
    - Documents
    - Downloads
    - Images
    - Library
    - Music
    - Notebooks
    - Recordings
    - Sessions
    - Videos
    - Workspace
