---

- name: configure user specific stuff
  hosts: localhost
  become: True
  gather_subset:
    - hardware
    - network
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/.cargo/bin"
  vars_files:
    - "vars/user.yml"

  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    DISPLAY: ":0"
    ZSH: "/usr/local/share/oh-my-zsh"

  pre_tasks:


  roles:
    - role: user
      tags: ['user']
    - role: home
      tags: ['home']

  post_tasks:

      - name: cleanup old backup files
        script: /usr/local/bin/cleanup.sh
        when: cleanup is defined
        tags: ['cleanup']
