---

- name: configure user specific stuff
  hosts: all
  tags: ['ui']
  become: True
  gather_subset:
    - hardware
    - network
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/.cargo/bin"

  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    ZSH: "/usr/local/share/oh-my-zsh"
    DISPLAY: ":0"

  pre_tasks:

    - name: ensure usr local directories exist
      file:
        path: "{{ item  }}"
        state: directory
        mode: '0755'
        recurse: False
      with_items:
        - "/usr/local/share/fonts/"
        - "/usr/local/share/icons"
        - "/usr/local/share/pixmaps/"
        - "/usr/local/share/themes"
        - "/usr/share/backgrounds/syncopated"
      tags: ['folders']

  tasks:

    - name: include vars
      include_vars:
        file: vars/distro/{{ ansible_distribution }}.yml

    - name: include user vars
      include_vars:
        dir: vars
        depth: 1
      tags: ['home', 'x11', 'shell', 'i3', 'theme', 'terminal']

    - import_tasks: tasks/ui/main.yml

  post_tasks:

      - name: cleanup old backup files
        script: /usr/local/bin/cleanup.sh
        when: cleanup is defined
        tags: ['cleanup']
