---

- name: configure ui
  hosts: all
  tags: ['ui']
  become: True
  gather_subset:
    - hardware
    - network
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/.cargo/bin"

  vars_files:
    - "vars/user.yml"

  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    ZSH: "/usr/local/share/oh-my-zsh"
    DISPLAY: ":0"

  pre_tasks:

    - name: Ensure usr local directories exist
      file:
        path: "{{ item  }}"
        state: directory
        mode: '0755'
        recurse: False
      with_items:
        - "/usr/local/share/fonts/"
        - "/usr/local/share/icons"
        - "/usr/local/share/pixmaps/"
        - "/usr/local/share/themes"
        - "/usr/share/backgrounds/ohmannium"
      tags: ['theme']

  tasks:

    - name: Include distro vars
      include_vars:
        file: vars/distro/{{ ansible_distribution }}.yml

    - name: Include user vars
      include_vars:
        dir: vars
        depth: 1
      tags: ['home', 'x11', 'shell', 'i3', 'theme', 'terminal', 'menu', 'keybindings', 'profile']

    - name: Set background location variable
      set_fact:
        backgrounds: "/usr/share/backgrounds/ohmannium"
      tags: ['theme']

    - import_tasks: tasks/ui/main.yml

    - import_tasks: tasks/ui/home.yml
      tags: ['home']

    - import_tasks: tasks/ui/x11.yml
      tags: ['x11']

    - import_tasks: tasks/ui/theme.yml
      tags: ['theme']

    - import_tasks: tasks/ui/menu.yml
      tags: ['menu']

  post_tasks:

      - name: Cleanup old backup files
        script: /usr/local/bin/cleanup.sh
        when: cleanup is defined
        tags: ['cleanup']
