---

- name: configure user specific stuff
  hosts: all
  become: True
  gather_subset:
    - hardware
    - network
  vars:
    path:
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/.cargo/bin"
  vars_files:
    - "vars/distro/{{ ansible_distribution }}.yml"
    - "vars/user.yml"
    - "vars/ui.yml"

  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/bin:{{ path|join(':') }}"
    ZSH: "/usr/local/share/oh-my-zsh"
    DISPLAY: ":0"

  pre_tasks:

  tasks:

    - include_tasks: tasks/ui/main.yml
      tags: ['ui']

  post_tasks:

      - name: cleanup old backup files
        script: /usr/local/bin/cleanup.sh
        when: cleanup is defined
        tags: ['cleanup']
