---

- name: setup libvirt and docker hosts
  hosts: devel
  become: True
  gather_subset:
    - hardware
    - network
  vars_files:
    - "vars/distro/{{ ansible_distribution }}.yml"
    - "vars/user.yml"
  roles:
    - role: virt
      tags: ['virt']
